Repository harshvardhansb/TourGuide, pull requests merged in 2022-10, with the labels that each got.

#44 Update Contribute.md
  Contribute.md
Labels: spam

#75 Added icon visibility
  index.html
Labels: hacktoberfest-accepted, NOICE, hacktoberfest

#76 #74 Resolved
  index.html
  slider/India.jpg
  style.css
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#125 Added the DhanushKodi tour guide , and corrected the pre existing errors.
  images/danushkodi.jpg
  index.html
Labels: hacktoberfest-accepted, hacktoberfest
